
;sekalaiset
(progn
(global-unset-key (kbd "C-#"))
;(global-unset-key (kbd "C-l"))
;(global-unset-key (kbd "C-t"))
(global-unset-key (kbd "C-f"))
(global-unset-key (kbd "C-t"))

(global-set-key (kbd "<C-f12>") 'nayta-flow)
(global-set-key (kbd "<C-f1>") 'biisit)
(global-set-key (kbd "<f2>") 'own-replace-regexp)
(global-set-key (kbd "<S-f2>") 'replace-string)
(global-set-key (kbd "<C-f2>") 'query-replace-regexp)
(global-set-key (kbd "<M-f2>") 'keep-lines)
(global-set-key (kbd "<S-M-f2>") 'flush-lines)

(global-set-key (kbd "<S-C-M-f10>") 'avaa-pika-leike)
(global-set-key (kbd "<S-C-M-f11>") 'avaa-muotoilut)
;(global-set-key (kbd "<S-C-M-f4>") 'avaa-ftp-tiedosto)
(global-set-key (kbd "C-f =") 'avaa-ftp-tiedosto)
(global-set-key (kbd "<S-C-M-f5>") 'avaa-leike-tiedosto)
(global-set-key (kbd "<S-C-M-f6>") 'avaa-vertailu-tiedosto)
(global-set-key (kbd "<S-C-M-f7>") 'avaa-haut-tiedosto)
(global-set-key (kbd "<S-C-M-f8>") 'avaa-lista-tiedosto)
(global-set-key (kbd "<S-C-M-f9>") 'avaa-relaatio-tiedosto)
(global-set-key (kbd "<S-f12>") 'talleta-flow)
;(global-set-key (kbd "<S-f1>") 'rename-buffer)
(global-set-key (kbd "<f12>") 'kirjoita-flow-temp)
(global-set-key (kbd "<f11>") 'kirjoita-muistiinpano)
;(global-set-key (kbd "<f4>") 'sulje-rml)
(global-set-key (kbd "C-# C-m C-l") 'avaa-rml)
(global-set-key (kbd "C-,") 'next-buffer)
(global-set-key (kbd "C-;") 'previous-buffer)
;(global-set-key (kbd "C-?") 'etsi-kysymys)
(global-set-key (kbd "C-f o e") 'avaa-excelissa)
(global-set-key (kbd "C-f o f") 'find-file)
(global-set-key (kbd "C-f o p") 'browse-url-at-point)
(global-set-key (kbd "C-f o t") 'avaa-tauluna)
(global-set-key (kbd "C-f s a") 'write-file)
(global-set-key (kbd "C-f s f") 'save-buffer)
;(global-set-key (kbd "C-l s") 'lataa-s)
(global-set-key (kbd "C-t =") 'avaa-tyot)
;(global-set-key (kbd "C-ö +") 'lisaa-muistilistaan) 
;(global-set-key (kbd "C-ö -") 'kuittaa-muistilistaan) 
;(global-set-key (kbd "C-ö =") 'nayta-muistilista) 
(global-unset-key (kbd "M-f"))
(global-set-key (kbd "M-f k e p") 'tyot-k-e-p)
(global-set-key (kbd "M-f =") 'kustomoi)
(global-set-key (kbd "M-f a a") 'tyot-avaa-aikataulut)
(global-set-key (kbd "M-f a v") 'tyot-radio)
(global-set-key (kbd "M-f 5") 'sana-5-rnd)
)
