(defun sana-leikepoydalle ()
  (interactive)
  (re-search-forward "\\w+" 99999 t)
    (leike-aseta-merkkijono (match-string 0)))

(defun relaation-alkio-leikepoydalle ()
  (interactive)
  (re-search-forward "[^;]*" 99999 t)
    (leike-aseta-merkkijono (match-string 0)))

(defun rivi-leikepoydalle ()
  (interactive)
  (beginning-of-line)
  (re-search-forward ".*" 99999 t)
  (leike-aseta-merkkijono (match-string 0))
  (forward-char))

(defun rivi-loppu-leikepoydalle ()
  (interactive)
  (re-search-forward ".*" 99999 t)
  (leike-aseta-merkkijono (match-string 0))
  (forward-char))

(defun tayta-relaatio ()
  (interactive)
  (forward-char)
  (beginning-of-line)
  (re-search-forward ".*" 99999 t)
  (leike-aseta-merkkijono (match-string 0))
  (insert ";"))

(defun merkkijono-leikepoydalle ()
  (interactive)
  (re-search-forward "[^ \t\n]+" 99999 t)
  (leike-aseta-merkkijono (match-string 0))
  (forward-char))

(defun merkkijono-leikepoydalle-siirry-alas ()
  (interactive)
  (setq paikka-rivilla (- (point) (line-beginning-position)))
  (save-excursion 
    (re-search-forward "[^ \t\n]+" 99999 t)
    (leike-aseta-merkkijono (match-string 0)))
  (forward-line)
  (forward-char paikka-rivilla))

(defun kappale-leikepoydalle ()
; taitaa toimia myös puskurin lopussa
  (interactive)
  (beginning-of-line)
  (re-search-forward "\\(\\(.+\\)\n?\\)+" nil t)
  (leike-aseta-merkkijono (match-string 0))
  (forward-char))

(defun 20-rivia-leikepoydalle ()
  (interactive)
  (beginning-of-line)
  (setq alku (point))
  (dotimes (x 20)
    (forward-line))
  (leike-aseta-merkkijono (substring (buffer-string) alku (- (point) 1))))

                 
(global-set-key (kbd "<f10>") 'sana-leikepoydalle)
(global-set-key (kbd "C-'") 'rivi-leikepoydalle)
(global-set-key (kbd "M-§") 'rivi-leikepoydalle)
(global-set-key (kbd "<backtab>") 'rivi-leikepoydalle)
(global-set-key (kbd "<S-C-f10>") 'rivi-loppu-leikepoydalle)
(global-set-key (kbd "<C-f10>") 'merkkijono-leikepoydalle)
;(global-set-key (kbd "<S-C-f10>") 'relaation-alkio-leikepoydalle)
;(global-set-key (kbd "<S-C-f10>") 'merkkijono-leikepoydalle-siirry-alas)
;(global-set-key (kbd "<S-C-f10>") 'rivi-toiseen-ikkunaan)
(global-set-key (kbd "<M-f10>") 'kappale-leikepoydalle)
(global-set-key (kbd "<S-M-f10>") '20-rivia-leikepoydalle)
